name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  job_id:
    # Any runner supporting Node 20 or newer
    runs-on: ubuntu-latest

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v4'

    - uses: 'google-github-actions/auth@v3'
      with:
        project_id: 'project-7b4216e1-eca3-49b8-bca'
        workload_identity_provider: 'projects/742749349988/locations/global/workloadIdentityPools/github-demo-pool/providers/github/attribute.repository/SGBooky/Pokemon-TCGPlayer-Webscraping'

