name: Scrape TCGPlayer → Google Sheets
run-name: ${{ github.actor }} is scraping TCGPlayer 🚀
#change to on: to like every day or so
on: [push]

jobs:
  scrape:
    runs-on: ubuntu-latest

    # Required permissions for Workload Identity Federation
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout repo
      uses: 'actions/checkout@v4'

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Chromium
      run: npx playwright install chromium

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2' # Note: v2 is the standard stable version
      with:
        project_id: 'project-7b4216e1-eca3-49b8-bca'
        # FIX 1: Point to the Provider path
        workload_identity_provider: 'projects/742749349988/locations/global/workloadIdentityPools/github-demo-pool/providers/github'
        # FIX 2: Specify the Service Account to impersonate
        service_account: 'pokemon-webscraper@project-7b4216e1-eca3-49b8-bca.iam.gserviceaccount.com'

    # Example step to verify it works
    - name: 'Verify Auth'
      run: |-
        gcloud auth list
        gcloud iam service-accounts list

    - name: Debug working directory
      run: |
        pwd
        ls -la
        find . -maxdepth 3 -type f

    - name: Run scrapper
      run: node src/index.js
